export const testAlbums = [
  {
    id: "1",
    name: "One of Wun",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "2",
    name: "DS4Ever",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "3",
    name: "Wunna",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "4",
    name: "Drip or Drown 2",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "5",
    name: "Drip Season 3",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "6",
    name: "Drip Season 2",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "7",
    name: "Drip Season 1",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "8",
    name: "Drip or Drown",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "9",
    name: "Drip Season 4",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "10",
    name: "Drip Season 5",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "11",
    name: "Drip Season 6",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "12",
    name: "Drip Season 7",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "13",
    name: "Drip Season 8",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "14",
    name: "Drip Season 9",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "15",
    name: "Drip Season 10",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "16",
    name: "Drip Season 11",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "17",
    name: "Drip Season 12",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "18",
    name: "Drip Season 13",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "19",
    name: "Drip Season 14",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "20",
    name: "Drip Season 15",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "21",
    name: "Drip Season 16",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "22",
    name: "Drip Season 17",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "23",
    name: "Drip Season 18",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "24",
    name: "Drip Season 19",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "25",
    name: "Drip Season 20",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "26",
    name: "Drip Season 21",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "27",
    name: "Drip Season 22",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "28",
    name: "Drip Season 23",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "29",
    name: "Drip Season 24",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "30",
    name: "Drip Season 25",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "31",
    name: "Drip Season 26",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "32",
    name: "Drip Season 27",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "33",
    name: "Drip Season 28",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "34",
    name: "Drip Season 29",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "35",
    name: "Drip Season 30",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "36",
    name: "Drip Season 31",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "37",
    name: "Drip Season 32",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "38",
    name: "Drip Season 33",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "39",
    name: "Drip Season 34",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "40",
    name: "Drip Season 35",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "41",
    name: "Drip Season 36",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "42",
    name: "Drip Season 37",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "43",
    name: "Drip Season 38",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "44",
    name: "Drip Season 39",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "45",
    name: "Drip Season 40",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "46",
    name: "Drip Season 41",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "47",
    name: "Drip Season 42",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "48",
    name: "Drip Season 43",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "49",
    name: "Drip Season 44",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
  {
    id: "50",
    name: "Drip Season 45",
    photo: "/assets/images/gunna.jpg",
    artist: "Gunna",
  },
];
